# This is a basic workflow to help you get started with Actions

name: updateState

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      now_time:
        required: true
        type: stirng
      c_temp:
        required: true
        type: string
      c_hum:
        required: true
        type: string
      l_temp:
        required: true
        type: string
      l_hum:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # print-inputs:
  #   name: Print Inputs
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print data
  #       run: echo "Data- ${{ github.event.inputs.c_temp }}"
  #     - name: Print data2
  #       run: echo "Data2- ${{ inputs.c_temp }}"
        
  modify-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Modify .txt file
      run: |
        echo "${{inputs.now_time}}" >> ./data.txt
        echo "${{inputs.c_temp}}" >> ./data.txt
        echo "${{inputs.c_hum}}" >> ./data.txt
        echo "${{inputs.l_temp}}" >> ./data.txt
        echo "${{inputs.l_hum}}" >> ./data.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./data.txt
        git commit -m "Update .txt file from GitHub Actions"
    
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push